services:
  demo:
  #kml:
  tms:
    # needs no arguments
  wms:
    # srs: ['EPSG:4326', 'EPSG:900913']
    image_formats: ['image/jpeg', 'image/png']
    md:
      # metadata used in capabilities documents
      title: Mars CTX WMS Proxy
      abstract: Provides a proxy service to the multiresolution CTX image tiles available in Google Cloud Storage 
      online_resource: http://mapproxy.org/
      contact:
        person: Ted Scharff
        position: Mapmaker
        organization: NASA Ames Research Center
        #address: Fakestreet 123
        city: Mountain View
        state: California
#        postcode: 12345#
#        country: Germany#
#        phone: +49(0)000-000000-0#
#        fax: +49(0)000-000000-0#
        email: e.b.scharff@nasa.gov
      access_constraints:
        This service is intended for private and evaluation use only.
      fees: 'None'

layers:
  - name: CTX
    title: CTX Mosaic
    sources: [ctx_cache]
    supported_srs: ['EPSG:4326']
    
caches:
  ctx_cache:
    #grids: [GLOBAL_MERCATOR, global_geodetic_sqrt2]
    grids: [global_mars]
    sources: [ctx_tiles]
  


sources:
  ctx_tiles:
    type: tile
    grid: global_mars
    url: http://commondatastorage.googleapis.com/ctx_mosaic_1/%(quadkey_path)s.png
    transparent: true
    format: ['image/png', 'image/jpg']
    supported_srs: ['EPSG:4326']
    #supported_srs: ['IAU2000:49900']
    on_error:
      404:
        response: transparent
        cache: true
      other:
        response: '#ff0000'
        cache: false

    

  # overlay_full_example:
  #   type: wms
  #   concurrent_requests: 4
  #   wms_opts:
  #     version: 1.3.0
  #     featureinfo: true
  #   supported_srs: ['EPSG:4326', 'EPSG:31467']
  #   supported_formats: ['image/tiff', 'image/jpeg']
  #   http:
  #     ssl_no_cert_checks: true
  #   req:
  #     url: https://user:password@example.org:81/service?
  #     layers: roads,rails
  #     styles: base,base
  #     transparent: true
  #     # # always request in this format
  #     # format: image/png
  #     map: /home/map/mapserver.map
    

grids:
  global_geodetic_sqrt2:
    base: GLOBAL_GEODETIC
    res_factor: 'sqrt2'
    origin: nw
    srs: 'EPSG:900913'
  global_mars:
    srs: 'EPSG:4326'
    origin: nw
  # grid_full_example:
  #   tile_size: [512, 512]
  #   srs: 'EPSG:900913'
  #   bbox: [5, 45, 15, 55]
  #   bbox_srs: 'EPSG:4326'
  #   min_res: 2000 #m/px
  #   max_res: 50 #m/px
  #   align_resolutions_with: GLOBAL_MERCATOR
  # another_grid_full_example:
  #   srs: 'EPSG:900913'
  #   bbox: [5, 45, 15, 55]
  #   bbox_srs: 'EPSG:4326'
  #   res_factor: 1.5
  #   num_levels: 25

globals:
  # # coordinate transformation options
  # srs:
  #   # WMS 1.3.0 requires all coordiates in the correct axis order,
  #   # i.e. lon/lat or lat/lon. Use the following settings to
  #   # explicitly set a CRS to either North/East or East/North
  #   # ordering.
  #   axis_order_ne: ['EPSG:9999', 'EPSG:9998']
  #   axis_order_en: ['EPSG:0000', 'EPSG:0001']
  #   # you can set the proj4 data dir here, if you need custom
  #   # epsg definitions. the path must contain a file named 'epsg'
  #   # the format of the file is:
  #   # <4326> +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs  <>
  #   proj_data_dir: '/path to dir that contains epsg file'

  # # cache options
  cache:
    # where to store the cached images
    base_dir: './cache_data'
    # where to store lockfiles
    lock_dir: './cache_data/locks'
    grid: global_mars
  #   # request x*y tiles in one step
  #   meta_size: [4, 4]
  #   # add a buffer on all sides (in pixel) when requesting
  #   # new images
  #   meta_buffer: 80


  # image/transformation options
  image:
      resampling_method: nearest
      # resampling_method: bilinear
      # resampling_method: bicubic
  #     jpeg_quality: 90
  #     # stretch cached images by this factor before
  #     # using the next level
  #     stretch_factor: 1.15
  #     # shrink cached images up to this factor before
  #     # returning an empty image (for the first level)
  #     max_shrink_factor: 4.0
